# Database Configuration Template
#database.type=mysql
#database.type=postgresql
#database.mysql.host=localhost
#database.mysql.password=
#database.mysql.username=root
#database.mysql.version=8.0
#database.postgresql.host=localhost
#database.postgresql.password=
#database.postgresql.username=root

#Test configuration
custom.upgrade.properties=module.framework.properties.osgi.console=${line.separator}virtual.hosts.valid.hosts=localhost,127.0.0.1,www.able.com${line.separator}property3=value3${line.separator}property4=value4
custom.startup.timeout=3600
#database.partition.enabled=true
#liferay.online.properties=true

# Database to upgrade (get it from upgrade poshi tests)
portal.legacy.dir=../liferay-qa-portal-legacy-ee
data.archive.type=data-archive-portal-partition
portal.version=7.4.13.u33
#data.archive.type=data-archive-portal-partition-large
#portal.version=2024.q2.3

# Don't start the app server and don't run the selenium test
skip.start.app.server=true
skip.run.selenium.test=true

# JVM Options
#
# Yourkit:
#database.upgrade.client.jvm.opts=-agentpath:<profiler directory>/bin/linux-x86-64/libyjpagent.so
# Remote debugger:
#database.upgrade.client.jvm.opts=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8000

# We have to add a test.class to enable the get-testcase-property macro logic to get these properties
test.class=dummy