{{- $iamRoleName := "liferay-backup-controller" -}}
apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
kind: ProjectIAMCustomRole
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-60"
    name: {{ $iamRoleName }}
spec:
    forProvider:
        permissions:
            -   cloudsql.backupRuns.create
            -   cloudsql.backupRuns.delete
            -   cloudsql.databases.list
            -   cloudsql.instances.export
            -   cloudsql.instances.get
            -   cloudsql.instances.list
            -   cloudsql.instances.update
            -   storage.buckets.get
            -   storage.buckets.list
            -   storage.objects.delete
            -   storage.objects.list
            -   storagetransfer.jobs.create
            -   storagetransfer.jobs.delete
            -   storagetransfer.jobs.get
            -   storagetransfer.jobs.run
            -   storagetransfer.operations.get
            -   storagetransfer.operations.list
            -   storagetransfer.projects.getServiceAccount
        project: {{ .Values.gcp.projectId }}
        title: Liferay Backup Controller Role
---
apiVersion: cloudplatform.gcp.m.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "-30"
    name: {{ $iamRoleName }}-binding
spec:
    forProvider:
        member: principal://iam.googleapis.com/projects/{{ .Values.gcp.projectNumber }}/locations/global/workloadIdentityPools/{{ .Values.gcp.projectId }}.svc.id.goog/subject/ns/{{ .Release.Namespace }}/sa/{{ .Values.serviceAccountName }}
        project: {{ .Values.gcp.projectId }}
        role: {{ printf "projects/%s/roles/%s" .Values.gcp.projectId $iamRoleName }}